version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017" # Mappe le port MongoDB par défaut de l'hôte au conteneur
    volumes:
      - mongodb_data:/data/db # Volume persistant pour les données MongoDB
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # Exemple pour un script d'initialisation
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin # Décommenter et définir pour un utilisateur root
      # - MONGO_INITDB_ROOT_PASSWORD=password # Décommenter et définir pour un mot de passe root
      - MONGO_INITDB_DATABASE=OA # Nom de la base de données par défaut

volumes:
  mongodb_data: # Déclaration du volume nommé pour la persistance des données
